# Generated by Django 2.0.1 on 2018-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250)),
                ('event_artist', models.CharField(max_length=250)),
                ('event_logo', models.CharField(max_length=1000)),
                ('event_fbPage', models.CharField(max_length=250)),
                ('time', models.DateField(verbose_name='Event Date:')),
                ('event_tkPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('information', models.CharField(max_length=10000)),
                ('event_stage1_name', models.CharField(max_length=50)),
                ('event_stage1_artists', models.CharField(max_length=350)),
                ('event_stage2_name', models.CharField(max_length=50)),
                ('event_stage2_artists', models.CharField(max_length=350)),
                ('event_stage3_name', models.CharField(max_length=50)),
                ('event_stage3_artists', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='music/static/assets/css/images')),
            ],
        ),
    ]
