# Generated by Django 2.0.1 on 2018-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_stage1_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage2_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage3_name',
            field=models.CharField(max_length=250),
        ),
    ]
