# Generated by Django 2.0.1 on 2018-02-08 17:50

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180208_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_artist',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage2_artists',
            field=models.CharField(default=music.models.Event.default_metki, max_length=350),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage2_name',
            field=models.CharField(default=music.models.Event.default_metki, max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage3_artists',
            field=models.CharField(default=music.models.Event.default_metki, max_length=350),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stage3_name',
            field=models.CharField(default=music.models.Event.default_metki, max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='information',
            field=models.TextField(max_length=100000),
        ),
    ]
