# Generated by Django 2.0.2 on 2018-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180205_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_fbPage',
            field=models.CharField(default='N/A', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_tkPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateField(verbose_name='Event Date:'),
        ),
    ]
